name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout-sp
      uses: actions/checkout@v2
      with: 
        path: sp

    - name: Installs
      run: |
        sudo apt-get install doxygen graphviz libnetcdf-dev libnetcdff-dev

    - name: build_wrf_io
      env: 
        FC: gfortran-9
        CC: gcc-9
      run: |
        set -x
        sudo find / -name netcdf.h -print
        cd sp
        mkdir build 
        cd build
        cmake ..
        make 

